id: AB0C948A7
title: Prayer for this Life, the Next and the Bardos
type: translation
pechas:
- IBFBFFBD7
- IE48A3230
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:51:47.880112
  last_modified_at: 2023-01-04 12:51:47.880135
  collections:
  - Khenchen Ngawang Palzang Series
  - Works of Tibetan Masters
alignment_to_base:
  IBFBFFBD7/9908: 5B9A
  IE48A3230/8F83: 5B9A
